CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Otorgar privilegios sobre los objetos
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO USUARIOPPTO;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO USUARIOPPTO;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO USUARIOPPTO;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO USUARIOPPTO;